### ISSUE TITLE
运行报错UnicodeEncodeError: 'ascii' codec can't encode characters in position 62-68: ordinal not in range(128)

### ISSUE THREAD

**Issue by colingpt** [jerrymakesjelly/autoremove-torrents#12]
## 出错情形：
增加了`seed_size:` 条件后报错，但种子和内容确实被删除了

## config.yml：
```
# A task block
my_task:                       # Part 1: Task Name
  # Part 2: Login Information
  client: qbittorrent
  host: http://127.0.0.1:xxxx
  username: xxx
  password: xxx
  # Part 3: Strategies Block (Remove Conditions)
  strategies:
    # Part I: Strategy Name
    strategy1:
      # Part II: Filters
      all_categories: true
      # Part III: Remove Condition
      seeding_time: 86400
    strategy2:
      all_categories: true
      seed_size:
        limit: 1000
        action: remove-old-seeds
  # Part 4: Decide whether to remove and delete data (optional)
  delete_data: true

# Add more tasks here...

```

## 报错内容如下：
```
Fri, 21 Dec 2018 15:38:22 autoremovetorrents.task INFO: The torrent [\u706b\u738b\u4e4b\u7834\u6653\u4e4b\u6218].The.King.of.Blaze.2018.Complete.WEB-DL.1080p.H264.AAC-CMCTV and its data have been removed.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 62-68: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/autoremove-torrents", line 11, in <module>
    load_entry_point('autoremove-torrents==1.2.4', 'console_scripts', 'autoremove-torrents')()
  File "/usr/local/lib/python3.5/dist-packages/autoremove_torrents-1.2.4-py3.5.egg/autoremovetorrents/main.py", line 62, in main
    pre_processor(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/autoremove_torrents-1.2.4-py3.5.egg/autoremovetorrents/main.py", line 49, in pre_processor
    Task(task_name, result[task_name], not view_mode).execute()
  File "/usr/local/lib/python3.5/dist-packages/autoremove_torrents-1.2.4-py3.5.egg/autoremovetorrents/task.py", line 119, in execute
    self._remove_torrents()
  File "/usr/local/lib/python3.5/dist-packages/autoremove_torrents-1.2.4-py3.5.egg/autoremovetorrents/task.py", line 108, in _remove_torrents
    self._logger.info('The torrent %s and its data have been removed.', torrent.name)
Message: 'The torrent %s and its data have been removed.'
Arguments: ('[\u706b\u738b\u4e4b\u7834\u6653\u4e4b\u6218].The.King.of.Blaze.2018.Complete.WEB-DL.1080p.H264.AAC-CMCTV',)
```

**Comment by colingpt** [comment]
已解决，是系统环境字符集设置的问题。

在‘/etc/default/locale‘添加如下：
···
LANG=zh_CN.UTF-8
LC_ALL=zh_CN.UTF-8
···
即可。

祝考研顺利！：P
