### ISSUE TITLE
Fails to run on Ubuntu 22.04

### ISSUE THREAD

**Issue by Pantar2205** [jerrymakesjelly/autoremove-torrents#129]
Worked flawlessly on 20.04. After update, it fials giving error =

```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/autoremove-torrents", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'autoremove-torrents==1.5.3' distribution was not found and is required by the application
```

**Comment by jerrymakesjelly** [comment]
Please provide your Python version and your command of installation.

**Comment by Pantar2205** [comment]
`Python 3.10.4`

Install method = github instructions

**Comment by Pantar2205** [comment]
wiped everything and started over.

github install again as per above.

copied config file back over.

output = 

```
Traceback (most recent call last):
  File "/usr/local/bin/autoremove-torrents", line 33, in <module>
    sys.exit(load_entry_point('autoremove-torrents==1.5.3', 'console_scripts', 'autoremove-torrents')())
  File "/usr/local/bin/autoremove-torrents", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/autoremove_torrents-1.5.3-py3.10.egg/autoremovetorrents/main.py", line 8, in <module>
  File "/usr/local/lib/python3.10/dist-packages/autoremove_torrents-1.5.3-py3.10.egg/autoremovetorrents/task.py", line 9, in <module>
  File "/usr/local/lib/python3.10/dist-packages/autoremove_torrents-1.5.3-py3.10.egg/autoremovetorrents/client/deluge.py", line 2, in <module>
ModuleNotFoundError: No module named 'deluge_client'
```

Note. I do not use deluge or have anything about i in my config. my config is =

```
my_task:
  client: qbittorrent
  host: IP_ADDRESS
  username: USERNAME
  password: PASSWORD
  strategies:
    my_strategy:
      categories: Done
      remove: seeding_time > 604800
  delete_data: true
```

**Comment by Pantar2205** [comment]
python3 setup.py install
as normal user fails as no write permission

running as sudo provides error = 
```

Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl#sha256=096f9b8350b65ebd2fd1346b12452efe5b9607f7482813ffca50c22722a807ce
error: Download error for https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl#sha256=096f9b8350b65ebd2fd1346b12452efe5b9607f7482813ffca50c22722a807ce: _ssl.c:980: The handshake operation timed out
```

**Comment by Pantar2205** [comment]
possibly a vpn issue. checking.

**Comment by Pantar2205** [comment]
Solved.

`python3 setup.py install`

must be run as sudo

the machine being conneced to a VPN may provoke download of required packages being blocked.

Solution = Disable VPN & install with sudo

**Comment by jerrymakesjelly** [comment]
Good. I will update the documents.

By the way I still recommend installing autoremove-torrents via `pip`.

**Comment by Pantar2205** [comment]
Oh ok. I am ignorant and don't know what that is or anything about it. I will have to take a look at it next chance I get. Thank you very much.
