### ISSUE TITLE
想放在小钢炮里，但发现不支持python2.x，能否支持一下py2？

### ISSUE THREAD

**Issue by Crazymmp** [jerrymakesjelly/autoremove-torrents#29]
在小钢炮里试了下，前面安装报错：TypeError: 'encoding' is an invalid keyword argument for this function
可以解决，
但是测试运行状态的时候会报错：ImportError: No module named parse
大佬请帮忙解决，谢谢！

**Comment by jerrymakesjelly** [comment]
可以

**Comment by Crazymmp** [comment]
大佬，今天用新版V1.4.2重新装了下，发现安装可以成功，最后输出如下：
Using /opt/lib/python2.7/site-packages
Finished processing dependencies for autoremove-torrents==1.4.2
然后测试AMT是否运行时，还是会有以下报错：
[root@phicomm-n1:~/autoremove-torrents]# /opt/bin/autoremove-torrents --view
Traceback (most recent call last):
  File "/opt/bin/autoremove-torrents", line 11, in <module>
    load_entry_point('autoremove-torrents==1.4.2', 'console_scripts', 'autoremove-torrents')()
  File "/opt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/lib/python2.7/site-packages/autoremove_torrents-1.4.2-py2.7.egg/autoremovetorrents/main.py", line 8, in <module>
  File "/opt/lib/python2.7/site-packages/autoremove_torrents-1.4.2-py2.7.egg/autoremovetorrents/task.py", line 12, in <module>
  File "/opt/lib/python2.7/site-packages/autoremove_torrents-1.4.2-py2.7.egg/autoremovetorrents/strategy.py", line 5, in <module>
  File "/opt/lib/python2.7/site-packages/autoremove_torrents-1.4.2-py2.7.egg/autoremovetorrents/filter/tracker.py", line 3, in <module>
ImportError: No module named parse

这个报错可以解决不？

**Comment by jerrymakesjelly** [comment]
> 这个报错可以解决不？

1.4.2不是解决Python 2.7的兼容性问题哦

有关兼容py2.7的代码我会提交到这个issue下面的

**Comment by jerrymakesjelly** [comment]
1.4.3已更新，感谢支持

**Comment by Crazymmp** [comment]
感谢大佬百忙之中抽出时间调试更新支持py2.7，我试了下V1.4.3，结果有点小问题，如下：
[root@phicomm-n1:/]# /opt/bin/autoremove-torrents --view
Mon, 20 May 2019 23:55:36 autoremovetorrents.main INFO: Auto Remove Torrents 1.4.3
Mon, 20 May 2019 23:55:36 autoremovetorrents.main INFO: Loading configurations...
Mon, 20 May 2019 23:55:36 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Running task 'my_task'...
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Logging in...
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.5.
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Getting all the torrents...
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Found 0 torrent(s) in the client.
Mon, 20 May 2019 23:55:36 autoremovetorrents.strategy INFO: Running strategy s1...
Mon, 20 May 2019 23:55:36 autoremovetorrents.main ERROR: AttributeError: 'set' object has no attribute 'sort'
Mon, 20 May 2019 23:55:36 autoremovetorrents.main ERROR: Task my_task fails. 
我去搜索了下这个AttributeError，说是可能是返回字符串没有成为列表啥的，就报错了，大佬您有空看看吧，我对这个还是太小白了。。。
