### ISSUE TITLE
centos7报错  ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by linanyang** [jerrymakesjelly/autoremove-torrents#3]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from autoremove import AutoRemover
  File "/root/autoremove-torrents/autoremove.py", line 8, in <module>
    from client.qbittorrent import qBittorrent
  File "/root/autoremove-torrents/client/qbittorrent.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
小白一个，不知道是不是哪里没设置对，帮忙看一下。

**Comment by jerrymakesjelly** [comment]
安装requests库即可：
pip3 install requests
