### ISSUE TITLE
autoremovetorrents.main ERROR: TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by mylovesaber** [jerrymakesjelly/autoremove-torrents#48]
命令：
```
autoremove-torrents --view --conf=/root/autoremove-torrents/config.yml
```
终端输出：
```
Fri, 13 Dec 2019 02:20:34 main.py[line:44] INFO Auto Remove Torrents 1.4.6
Fri, 13 Dec 2019 02:20:34 main.py[line:46] INFO Loading configurations...
Fri, 13 Dec 2019 02:20:34 main.py[line:49] INFO Found 1 task(s) in the file.
Fri, 13 Dec 2019 02:20:34 task.py[line:115] INFO Running task 'ttg'...
Fri, 13 Dec 2019 02:20:34 task.py[line:75] INFO Logging in...
Fri, 13 Dec 2019 02:20:34 task.py[line:80] INFO Login successfully. The client is qBittorrent v4.1.7.
Fri, 13 Dec 2019 02:20:34 task.py[line:84] INFO Getting all the torrents...
Fri, 13 Dec 2019 02:20:35 task.py[line:94] INFO Found 24 torrent(s) in the client.
Fri, 13 Dec 2019 02:20:35 strategy.py[line:82] INFO Running strategy ttg...
Fri, 13 Dec 2019 02:20:35 main.py[line:57] ERROR TypeError: unhashable type: 'slice'
Fri, 13 Dec 2019 02:20:35 main.py[line:58] ERROR Task ttg fails. 
Fri, 13 Dec 2019 02:20:35 main.py[line:59] DEBUG Exception Logged
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/autoremovetorrents/main.py", line 55, in pre_processor
    Task(task_name, result[task_name], not view_mode).execute()
  File "/usr/local/lib/python3.7/site-packages/autoremovetorrents/task.py", line 118, in execute
    self._apply_strategies()
  File "/usr/local/lib/python3.7/site-packages/autoremovetorrents/task.py", line 100, in _apply_strategies
    strategy.execute(self._torrents)
  File "/usr/local/lib/python3.7/site-packages/autoremovetorrents/strategy.py", line 87, in execute
    self._apply_conditions()
  File "/usr/local/lib/python3.7/site-packages/autoremovetorrents/strategy.py", line 75, in _apply_conditions
    cond.apply(self.remain_list)
  File "/usr/local/lib/python3.7/site-packages/autoremovetorrents/conditionparser.py", line 92, in apply
    self.parser.parse(self._expression)
  File "/usr/local/lib/python3.7/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.7/site-packages/ply/yacc.py", line 1026, in parseopt_notrack
    lexer.input(input)
  File "/usr/local/lib/python3.7/site-packages/ply/lex.py", line 253, in input
    c = s[:1]
TypeError: unhashable type: 'slice'
```
配置如下：
```
ttg:
  client: qbittorrent
  host: http://127.0.0.1:2017
  username: user
  password: admin
  strategies:
    ttg:
      categories:
        - ttg
      status:
        - stalledUpload
      remove: 
        maximum_number:
          limit: 1
          action:
            - remove-old-seeds
            - remove-big-seeds
  delete_data: true
```
请教下何处出错的呢？

**Comment by mylovesaber** [comment]
经作者指点，action只能用一个参数，不可列表显示，即：
`action: remove-old-seeds`
