### ISSUE TITLE
win10 python3.7.6 运行报错

### ISSUE THREAD

**Issue by szRayX** [jerrymakesjelly/autoremove-torrents#58]
在powershell中运行autoremove-torrents --view命令报错，如下：
`PS D:\Program Files\autoremove-torrents-1.4.8> autoremove-torrents --view --conf=D:/Program Files/autoremove-torrents-1.
4.8/config.yml
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python37\Scripts\autoremove-torrents-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 3250, in <module>
    @_call_aside
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'idna<2.9,>=2.5' distribution was not found and is required by requests`

**Comment by jerrymakesjelly** [comment]
目前 idna 的最新版本是2.8，应该符合 requests 库中 `idna<2.9,>=2.5` 的要求，要不更新一下 requests 库试试？

`pip install --upgrade requests`

**Comment by szRayX** [comment]
更新库后问题解决，非常感谢！
