### ISSUE TITLE
Causes qbittorrent to crash

### ISSUE THREAD

**Issue by aur3l14no** [jerrymakesjelly/autoremove-torrents#75]
Autoremove-torrents log
```
Sun, 24 May 2020 00:00:39 task.py[line:79] INFO Getting all the torrents...
Sun, 24 May 2020 00:01:38 task.py[line:87] INFO Please wait...We have found 1 torrent(s).
Sun, 24 May 2020 00:01:48 task.py[line:87] INFO Please wait...We have found 2 torrent(s).
Sun, 24 May 2020 00:02:07 task.py[line:87] INFO Please wait...We have found 3 torrent(s).
Sun, 24 May 2020 00:03:07 task.py[line:87] INFO Please wait...We have found 4 torrent(s).
Sun, 24 May 2020 00:04:09 main.py[line:58] ERROR json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sun, 24 May 2020 00:04:09 main.py[line:59] ERROR Task my_task fails.
Sun, 24 May 2020 00:04:09 main.py[line:60] DEBUG Exception Logged
Traceback (most recent call last):
  File "/home/y/miniconda3/lib/python3.7/site-packages/autoremovetorrents/main.py", line 56, in pre_processor
    Task(task_name, result[task_name], not view_mode).execute()
  File "/home/y/miniconda3/lib/python3.7/site-packages/autoremovetorrents/task.py", line 123, in execute
    self._get_torrents()
  File "/home/y/miniconda3/lib/python3.7/site-packages/autoremovetorrents/task.py", line 83, in _get_torrents
    self._torrents.add(self._client.torrent_properties(hash_value))
  File "/home/y/miniconda3/lib/python3.7/site-packages/autoremovetorrents/client/qbittorrent.py", line 169, in torrent_properties
    trackers = self._request_handler.torrent_trackers(torrent_hash).json()
  File "/home/y/miniconda3/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/y/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/y/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/y/miniconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

qBittorrent service log
```
May 24 00:04:08 localhost systemd[1]: qbittorrent.service: Main process exited, code=kill
May 24 00:04:08 localhost systemd[1]: qbittorrent.service: Failed with result 'signal'.
May 24 00:04:09 localhost systemd[1]: qbittorrent.service: Service RestartSec=100ms expir
May 24 00:04:09 localhost systemd[1]: qbittorrent.service: Scheduled restart job, restart
May 24 00:04:09 localhost systemd[1]: Stopped qBittorrent Daemon Service.
May 24 00:04:09 localhost systemd[1]: Started qBittorrent Daemon Service.
```

**Comment by jerrymakesjelly** [comment]
It seems that the response of qBittorrent is invalid. Which version of QB are you using?

Thanks for your feedback.

**Comment by aur3l14no** [comment]
> It seems that the response of qBittorrent is invalid. Which version of QB are you using?
v4.1.5

**Comment by mylovesaber** [comment]
Upgrade to at least version 4.1.9.Maybe some old versions of the qb client do not support these keywords.

**Comment by jerrymakesjelly** [comment]
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This error usually occurs when the connection is lost. And, when the connection is slow, the "Please wait" message will display every second.

So it seems that there is no problem with ART and QB. And I think improving your network environment can help you solve this problem.

**Comment by Mit2g** [comment]
Check this [issuse](https://github.com/jerrymakesjelly/autoremove-torrents/issues/81) if u met same error
